# Gemini did this.
version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: veryverystrongpassword
      MYSQL_DATABASE: image_catalog
